/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoadDatabase;
import Controller.controller;
import Model.LopTinChi;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Minh Thu
 */
public class QuanLyLopTinChi extends javax.swing.JFrame {
    
    private DefaultTableModel model;

    public QuanLyLopTinChi() {
        initComponents();
        LoadDatabase loadDatabase = new LoadDatabase();
        loadDatabase.fillComboBox(cmbKhoa, "tenKhoa", "KHOA");
        model = (DefaultTableModel) tbLopTinChi.getModel();
        model.setRowCount(0);
        tbLopTinChi.setRowHeight(20);
        cmbNienKhoa.removeAllItems();
        loadDatabase.fillDistinctComboBox(cmbNienKhoa, "nienKhoa", "HOCKY");
        btXemDSSVDK.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbHuyLop = new javax.swing.JCheckBox();
        tfMaLTC = new javax.swing.JTextField();
        tfSVMIN = new javax.swing.JTextField();
        tfNhom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfSVMAX = new javax.swing.JTextField();
        cmbLop = new javax.swing.JComboBox<>();
        cmbNienKhoa = new javax.swing.JComboBox<>();
        cmbHocKy = new javax.swing.JComboBox<>();
        cmbMonHoc = new javax.swing.JComboBox<>();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btNhapMoi = new javax.swing.JButton();
        btXemDSSVDK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmbKhoa = new javax.swing.JComboBox<>();
        btTimKiem = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLopTinChi = new javax.swing.JTable();
        btDKLTC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb.setText("Mã LTC");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Hủy lớp");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Môn học");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Học kỳ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Số svmin");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Niên khóa");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Số svmax");

        cbHuyLop.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        tfMaLTC.setEditable(false);
        tfMaLTC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfSVMIN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfNhom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Nhóm");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Lớp");

        tfSVMAX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbLop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbNienKhoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbHocKy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbHocKy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        cmbMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btThem.setBackground(new java.awt.Color(76, 124, 97));
        btThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btThem.setForeground(new java.awt.Color(255, 255, 255));
        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setBackground(new java.awt.Color(76, 124, 97));
        btXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btXoa.setForeground(new java.awt.Color(255, 255, 255));
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btSua.setBackground(new java.awt.Color(76, 124, 97));
        btSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSua.setForeground(new java.awt.Color(255, 255, 255));
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btNhapMoi.setBackground(new java.awt.Color(76, 124, 97));
        btNhapMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btNhapMoi.setForeground(new java.awt.Color(255, 255, 255));
        btNhapMoi.setText("Nhập mới");
        btNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapMoiActionPerformed(evt);
            }
        });

        btXemDSSVDK.setBackground(new java.awt.Color(76, 124, 97));
        btXemDSSVDK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btXemDSSVDK.setForeground(new java.awt.Color(255, 255, 255));
        btXemDSSVDK.setText("Xem DSSVDK");
        btXemDSSVDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXemDSSVDKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(tfSVMIN, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfSVMAX, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(cmbLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(27, 27, 27))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbNienKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfMaLTC)
                                            .addComponent(cmbMonHoc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(cmbHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfNhom, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbHuyLop, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(51, 51, 51)
                                            .addComponent(btNhapMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(51, 51, 51)
                                            .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(24, 24, 24)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btXemDSSVDK, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb)
                    .addComponent(tfMaLTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfNhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbNienKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfSVMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfSVMAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(cbHuyLop))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btXoa))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSua)
                    .addComponent(btNhapMoi))
                .addGap(26, 26, 26)
                .addComponent(btXemDSSVDK)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(209, 232, 195));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Student Management");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel4.setText("MoliSM");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý lớp tín chỉ");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("XX - Ten người dùng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        cmbKhoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbKhoa.setToolTipText("");
        cmbKhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKhoaItemStateChanged(evt);
            }
        });

        btTimKiem.setBackground(new java.awt.Color(76, 124, 97));
        btTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btTimKiem.setText("Tìm kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Khoa");

        tbLopTinChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbLopTinChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã LTC", "Mã môn học", "Tên môn học", "Mã học kỳ", "Lớp", "Nhóm", "Số SVMIN", "Số SVMAX", "Hủy lớp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLopTinChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLopTinChiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLopTinChi);
        if (tbLopTinChi.getColumnModel().getColumnCount() > 0) {
            tbLopTinChi.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbLopTinChi.getColumnModel().getColumn(1).setPreferredWidth(70);
            tbLopTinChi.getColumnModel().getColumn(2).setPreferredWidth(250);
            tbLopTinChi.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbLopTinChi.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbLopTinChi.getColumnModel().getColumn(5).setPreferredWidth(25);
            tbLopTinChi.getColumnModel().getColumn(6).setPreferredWidth(30);
            tbLopTinChi.getColumnModel().getColumn(7).setPreferredWidth(40);
            tbLopTinChi.getColumnModel().getColumn(8).setPreferredWidth(50);
        }

        btDKLTC.setBackground(new java.awt.Color(76, 124, 97));
        btDKLTC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDKLTC.setForeground(new java.awt.Color(255, 255, 255));
        btDKLTC.setText("Đăng ký lớp tín chỉ");
        btDKLTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDKLTCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDKLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTimKiem)
                    .addComponent(btDKLTC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKhoaItemStateChanged
        
    }//GEN-LAST:event_cmbKhoaItemStateChanged

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        if (evt.getSource() == btTimKiem) {
            showData();
        }
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        if (evt.getSource() == evt.getSource()) {
            try {
                if (cmbMonHoc.getSelectedItem().equals("") || cmbHocKy.getSelectedItem().equals("") || tfNhom.getText().equals("") || cmbNienKhoa.getSelectedItem().equals("") || cmbLop.getSelectedItem().equals("") || tfSVMIN.getText().equals("") || tfSVMAX.getText().equals("")) {
                    JOptionPane.showMessageDialog(rootPane, "Bạn phải điền đầu đủ thông tin!!", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                LopTinChi ltc = addLopTinChi();
                if (ltc == null) {
                    return;
                }
                Controller.InsertData.insertLopTinChi(ltc);
                showData();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(QuanLyLopTinChi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        if (evt.getSource() == btXoa) {
            try {
                int index = tbLopTinChi.getSelectedRow();
                int maLopTC = controller.arrayListLopTinChi.get(index).getMaLopTC();
                Controller.DeleteData.deleteLopTinChi(maLopTC);
                showData();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(QuanLyLopTinChi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        if (evt.getSource() == btSua) {
            try {
                if (cmbMonHoc.getSelectedItem().equals("") || cmbHocKy.getSelectedItem().equals("") || tfNhom.getText().equals("") || cmbNienKhoa.getSelectedItem().equals("") || cmbLop.getSelectedItem().equals("") || tfSVMIN.getText().equals("") || tfSVMAX.getText().equals("")) {
                    JOptionPane.showMessageDialog(rootPane, "Bạn phải điền đầu đủ thông tin!!", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                LopTinChi ltc = updateLopTinChi();
                if (ltc == null) {
                    return;
                }
                Controller.UpdateData.updateLopTinChi(ltc);
                showData();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(QuanLyLopTinChi.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapMoiActionPerformed
        if (evt.getSource() == btNhapMoi) {
            tfMaLTC.setText("");
            cmbMonHoc.setSelectedItem(null);
            cmbHocKy.setSelectedItem(null);
            tfNhom.setText("");
            cmbNienKhoa.setSelectedItem(null);
            cmbLop.setSelectedItem(null);
            tfSVMAX.setText("");
            tfSVMIN.setText("");
            cbHuyLop.setSelected(false);
        }
    }//GEN-LAST:event_btNhapMoiActionPerformed

    private void btDKLTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDKLTCActionPerformed
        if (evt.getSource() == btDKLTC){
            String tenKhoa = (String) cmbKhoa.getSelectedItem();
            new DangKyLTC(tenKhoa).setVisible(true);
        }
    }//GEN-LAST:event_btDKLTCActionPerformed

    private void tbLopTinChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLopTinChiMouseClicked
        try {
            int index = tbLopTinChi.getSelectedRow();
            LopTinChi ltc = controller.arrayListLopTinChi.get(index);
            tfMaLTC.setText(String.valueOf(ltc.getMaLopTC()));
            cmbMonHoc.setSelectedItem(LoadDatabase.getColumnFromMonHoc(ltc.getMaMH(), "tenMH", "maMH"));
            cmbHocKy.setSelectedItem(Integer.valueOf(ltc.getMaHK().substring(1, 2)));
            tfNhom.setText(String.valueOf(ltc.getNhom()));
            cmbNienKhoa.setSelectedItem(ltc.getMaHK().substring(3));
            cmbLop.setSelectedItem(ltc.getMaLop());
            tfSVMIN.setText(String.valueOf(ltc.getSvMin()));
            tfSVMAX.setText(String.valueOf(ltc.getSvMax()));
            cbHuyLop.setSelected(ltc.isHuyLop());
            btXemDSSVDK.setEnabled(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyLopTinChi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbLopTinChiMouseClicked

    private void btXemDSSVDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXemDSSVDKActionPerformed
        if(evt.getSource() == btXemDSSVDK) {
            int index = tbLopTinChi.getSelectedRow();
            LopTinChi ltc = controller.arrayListLopTinChi.get(index);
            new DanhSachSVDKLopTinChi(ltc).setVisible(true);
        }
    }//GEN-LAST:event_btXemDSSVDKActionPerformed
    
    public void showData() {
        try {
            String selectedValue = (String) cmbKhoa.getSelectedItem();
            LoadDatabase.loadTableLopTinChi(selectedValue);
            model.setRowCount(0);
            
            // duyệt danh sách lớp tín chỉ của 1 khoa
            for (LopTinChi ltc: controller.arrayListLopTinChi) {
                Object[] row = new Object[] {
                    ltc.getMaLopTC(), ltc.getMaMH(), LoadDatabase.getTenMH(ltc.getMaMH()), ltc.getMaHK(), 
                    ltc.getMaLop(), ltc.getNhom(), ltc.getSvMin(), ltc.getSvMax(), ltc.isHuyLop()
                }; 
                model.addRow(row);
            }
            
            // hiển thị cmbLop và cmbMH
            cmbMonHoc.removeAllItems();
            LoadDatabase.fillSubComboMonHoc(cmbMonHoc, selectedValue);
            cmbLop.removeAllItems();
            LoadDatabase.fillSubComboLopFromKhoa(cmbLop, selectedValue);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyLopTinChi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public LopTinChi addLopTinChi() {
        LopTinChi ltc = new LopTinChi();
        
        try {
            // check điều kiện nhập vào
            ltc.setMaLopTC(LoadDatabase.getMaLTC());
            tfMaLTC.setText(String.valueOf(ltc.getMaLopTC()));
            ltc.setMaMH(LoadDatabase.getColumnFromMonHoc(cmbMonHoc.getSelectedItem().toString() ,"maMH", "tenMH"));
            ltc.setMaHK("0".concat(cmbHocKy.getSelectedItem().toString() + "_" + cmbNienKhoa.getSelectedItem().toString()));
            ltc.setNhom(Integer.parseInt(tfNhom.getText()));
            ltc.setMaLop((String) cmbLop.getSelectedItem());
            
            // check điều kiện maMH, maHK, nhom, maLop không được trùng nhau
            for (LopTinChi loptinchi: controller.arrayListLopTinChi) {
                if (ltc.getMaLop().equals(loptinchi.getMaLop()) && ltc.getMaHK().equals(loptinchi.getMaHK()) && ltc.getMaMH().equals(loptinchi.getMaMH()) && ltc.getNhom() == loptinchi.getNhom()) {
                    JOptionPane.showMessageDialog(rootPane, "Mã môn hoc, mã lớp, nhóm, mã học kỳ đã tồn tại.", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
                    return null;
                }
            }
            ltc.setSvMin(Integer.parseInt(tfSVMIN.getText()));
            ltc.setSvMax(Integer.parseInt(tfSVMAX.getText()));
            if (ltc.getSvMax() < ltc.getSvMin()) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng sinh viên max không được nhỏ hơn số lượng sinh viên min!", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
                return null;
            }
            ltc.setHuyLop(cbHuyLop.isSelected()); 
//            ltc.setDssvdk(dssvdk);
            // thiếu dssvdk
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyLopTinChi.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ltc;
    }
    
    public LopTinChi updateLopTinChi() {
        int index = tbLopTinChi.getSelectedRow();
        LopTinChi ltc = controller.arrayListLopTinChi.get(index);
        
        try {
            // check điều kiện nhập vào
            ltc.setMaMH(LoadDatabase.getColumnFromMonHoc(cmbMonHoc.getSelectedItem().toString() ,"maMH", "tenMH"));
            ltc.setMaHK("0".concat(cmbHocKy.getSelectedItem().toString() + "_" + cmbNienKhoa.getSelectedItem().toString()));
            ltc.setNhom(Integer.parseInt(tfNhom.getText()));
            ltc.setMaLop((String) cmbLop.getSelectedItem());
            
            // check điều kiện maMH, maHK, nhom, maLop không được trùng nhau
            for (LopTinChi loptinchi: controller.arrayListLopTinChi) {
                if (ltc.getMaLop().equals(loptinchi.getMaLop()) && ltc.getMaHK().equals(loptinchi.getMaHK()) && ltc.getMaMH().equals(loptinchi.getMaMH()) && ltc.getNhom() == loptinchi.getNhom() && ltc.getMaLopTC() != loptinchi.getMaLopTC()) {
                    JOptionPane.showMessageDialog(rootPane, "Mã môn hoc, mã lớp, nhóm, mã học kỳ đã tồn tại.", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
                    return null;
                }
            }
            ltc.setSvMin(Integer.parseInt(tfSVMIN.getText()));
            ltc.setSvMax(Integer.parseInt(tfSVMAX.getText()));
            if (ltc.getSvMax() < ltc.getSvMin()) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng sinh viên max không được nhỏ hơn số lượng sinh viên min!", "Báo lỗi", JOptionPane.ERROR_MESSAGE);
                return null;
            }
            ltc.setHuyLop(cbHuyLop.isSelected()); 
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyLopTinChi.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ltc;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyLopTinChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyLopTinChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyLopTinChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyLopTinChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyLopTinChi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDKLTC;
    private javax.swing.JButton btNhapMoi;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXemDSSVDK;
    private javax.swing.JButton btXoa;
    private javax.swing.JCheckBox cbHuyLop;
    private javax.swing.JComboBox<String> cmbHocKy;
    private javax.swing.JComboBox<String> cmbKhoa;
    private javax.swing.JComboBox<String> cmbLop;
    private javax.swing.JComboBox<String> cmbMonHoc;
    private javax.swing.JComboBox<String> cmbNienKhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb;
    private javax.swing.JTable tbLopTinChi;
    private javax.swing.JTextField tfMaLTC;
    private javax.swing.JTextField tfNhom;
    private javax.swing.JTextField tfSVMAX;
    private javax.swing.JTextField tfSVMIN;
    // End of variables declaration//GEN-END:variables
}


